logbook_cso/logbook_cso/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls')),
]

logbook_cso/main/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^logbook/$', views.logbook, name='logbook'),
    url(r'^log_details/$', views.log_details, name='log_details'),
    url(r'log_form/$', views.log_form, name='log_form'),
    url(r'diary/$', views.diary, name='diary'),
    url(r'diary_event/$', views.diary, name='diary_event'),
    url(r'^service_user/(\d+)/', views.service_user_page, name='service_user_page'),
    url(r'^referral/(\d+)/', views.referral_page, name='referral_page'),
    url(r'graphs/$', views.graphs, name='graphs'),
    url(r'incident_form/$', views.incident_form, name='incident_form'),
    url(r'risk_form/$', views.risk_form, name='risk_form'),
    url(r'referral_form/$', views.referral_form, name='referral_form'),
    url(r'service_user_form/$', views.service_user_form, name='service_user_form'),
    url(r'service_user_form/(?P<def_ref>\d+)/$', views.service_user_form),
    url(r'diary_entry_form/$', views.diary_entry_form, name='diary_entry_form'),
    url(r'neighbour_complaint_form/$', views.neighbour_complaint_form, name='neighbour_complaint_form'),
    url(r'social_work_form/$', views.social_work_form, name='social_work_form'),
    url(r'vulnerable_young_adult_concerns_form/$', views.vulnerable_young_adult_concerns_form,
        name='vulnerable_young_adult_concerns_form'),
    url(r'child_protection_concern_form/$', views.child_protection_concern_form, name='child_protection_concern_form'),
    url(r'service_users_list/$', views.service_users_list, name='service_users_list'),
    url(r'referrals_list/$', views.referrals_list, name='referrals_list'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^password_reset/$', password_reset, name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete, name='password_reset_complete'),
]

logbook_cso/main/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# User is default Django user

class Referral(models.Model):
    # Gender choices
    MALE_CHOICE = 'M'
    FEMALE_CHOICE = 'F'
    OTHER_CHOICE = 'O'
    GENDER_CHOICES = (
        (MALE_CHOICE, 'Male'),
        (FEMALE_CHOICE, 'Female'),
        (OTHER_CHOICE, 'Other/Rather not disclose')
    )

    # ID - default
    # NIN
    nin = models.CharField(null=True, blank=True, max_length=10)
    # First name
    first_name = models.CharField(blank=False, max_length=128)
    # Last name
    last_name = models.CharField(blank=False, max_length=128)
    # Phone number
    phone = models.CharField(null=True, blank=True, max_length=16)
    # Email address
    email = models.EmailField(null=True, blank=True, max_length=128)
    # Date of birth
    dob = models.DateField()
    # Address
    address = models.TextField(blank=False, max_length=1024)
    # Referral date
    referral_date = models.DateField()
    # Referred by
    referred_by = models.CharField(null=True, blank=True, max_length=256)
    # Contact name
    contact_name = models.CharField(null=True, blank=True, max_length=256)
    # Contact phone
    contact_phone = models.CharField(null=True, blank=True, max_length=256)
    # Gender
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default=OTHER_CHOICE)
    # Reason
    reason = models.TextField(null=True, blank=True, max_length=1024)
    # Notes
    notes = models.TextField(null=True, blank=True, max_length=1024)
    # Doctor's name
    doctor_name = models.CharField(null=True, blank=True, max_length=256)
    # Doctor's phone
    doctor_phone = models.CharField(null=True, blank=True, max_length=16)
    # Doctor surgery address
    surgery_address = models.TextField(null=True, blank=True, max_length=1024)
    # If the user is banned
    is_banned = models.BooleanField(default=False)

    def __str__(self):
        return str(self.first_name) + " " + str(self.last_name)

    class Meta:
        ordering = ('-referral_date',)


class Service(models.Model):
    #The type of service
    service_type = models.CharField(max_length=64)
    #Description of the service
    description = models.TextField(null=True, blank=True, max_length=1024)

    def __str__(self):
        return self.service_type


class ServiceUser(models.Model):
    # ID - default
    # Date accepted
    date_accepted = models.DateField(null=False)
    # Health issues
    health_issues = models.TextField(null=True, blank=True)
    # Mental issues
    mental_issues = models.TextField(null=True, blank=True)
    # Drug issues
    drug_issues = models.TextField(null=True, blank=True)
    # Criminal background
    criminal_background = models.TextField(null=True, blank=True)
    # Alcohol issues
    alcohol_issues = models.TextField(null=True, blank=True)
    # Emotional issues
    emotional_issues = models.TextField(null=True, blank=True)
    # Is the service user pregnant
    is_pregnant = models.BooleanField(default=False)
    # Relation with the Referral class
    referral = models.OneToOneField(Referral, on_delete=models.CASCADE)

    def __str__(self):
        return self.referral.__str__()

    class Meta:
        ordering = ('-date_accepted',)


class UserUsesService(models.Model):
    #Service
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    #Service user
    service_user = models.ForeignKey(ServiceUser, on_delete=models.CASCADE)
    #Start date
    start_date = models.DateField(auto_now_add=True)


class LogEntry(models.Model):
    #Priority choices
    GREEN_PRIORITY = 'green'
    AMBER_PRIORITY = 'yellow'
    RED_PRIORITY = 'red'
    PRIORITY_CHOICES = (
        (GREEN_PRIORITY, 'Green'),
        (AMBER_PRIORITY, 'Yellow'),
        (RED_PRIORITY, 'Red')
    )

    #Log entry timestamp
    timestamp = models.DateTimeField(auto_now_add=True)
    #Priority
    priority = models.CharField(max_length=6,choices=PRIORITY_CHOICES, default=GREEN_PRIORITY)
    #Title
    title = models.CharField(max_length=256)
    #Description
    description = models.TextField(null=True, blank=True, max_length=1024)
    #Action required
    action_required = models.BooleanField(default=False)
    #Staff assigned to it
    assigned_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='assigned_user')
    #Service users involved
    service_users = models.ManyToManyField(ServiceUser, blank=True)
    #If this is a new version of a previous log entry
    previous_log_entry = models.OneToOneField("self", null=True, blank=True, default=None)
    #If the log entry is specifically related to a service
    service = models.ForeignKey(Service, blank=True, null=True)

    def has_previous_log_entry(self):
        return (self.previous_log_entry != None)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Log entries'
        ordering = ('-timestamp',)


class DiaryEntry(models.Model):
    #Appointment date
    appointment_date = models.DateField()
    #Details
    details = models.TextField(max_length=1024)
    #Service user
    service_user = models.ForeignKey(ServiceUser, on_delete=models.CASCADE, null=True, blank=True)
    #Staff user
    staff_user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.appointment_date)

    class Meta:
        verbose_name_plural = 'Diary entries'

class IncidentReport(models.Model):
    #Title
    title = models.CharField(max_length=256)
    #Date of incident
    incident_date = models.DateField()
    #Time of incident
    incident_time = models.TimeField()
    #Location of incident
    location = models.CharField(null=True, blank=True, max_length=256)
    #Brief description
    brief_description = models.CharField(null=True, blank=True, max_length=256)
    #Names of witnesses
    witnesses = models.TextField(null=True, blank=True, max_length=1024)
    #Apparent cause of incident
    cause = models.TextField(null=True, blank=True, max_length=1024)
    #Description of the incident
    description = models.TextField(null=True, blank=True, max_length=1024)
    #Action taken
    action_taken = models.TextField(null=True, blank=True, max_length=1024)
    #Police details
    police_details = models.TextField(null=True, blank=True, max_length=1024)
    #Medical assistance details
    medical_assistance_details = models.TextField(null=True, blank=True, max_length=1024)
    #Date of staff member debriefing
    debriefing_meeting_date = models.DateField()
    #Comments on action taken during incident
    comments_action_taken = models.TextField(null=True, blank=True, max_length=1024)
    #Comments on action required
    comments_action_required = models.TextField(null=True, blank=True, max_length=1024)
    #Proposed action brief
    brief_proposed_action = models.CharField(null=True, blank=True, max_length=256)
    #Linked log entry
    log_entry = models.OneToOneField(LogEntry, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class RiskAssessment(models.Model):

    #Risk level choices
    LOW_RISK = 1
    MEDIUM_RISK = 2
    HIGH_RISK = 3
    RISK_CHOICES = (
        (LOW_RISK, 'Low'),
        (MEDIUM_RISK, 'Medium'),
        (HIGH_RISK, 'High')
    )

    #Date of risk assessment
    date_assessed = models.DateField(default=datetime.date.today)
    #Review date
    review_date = models.DateField()
    #Activity for which risk assessment is being made
    activity = models.TextField(max_length=512)
    #Potential hazards
    hazards = models.TextField(max_length=1024, null=True, blank=True)
    #Existing control measures
    existing_control = models.TextField(max_length=1024, null=True, blank=True)
    #Additional control measures
    additional_control = models.TextField(max_length=1024, null=True, blank=True)
    #Initial risk assessment
    initial_risk = models.IntegerField(choices=RISK_CHOICES)
    #Residual risk assessment
    residual_risk = models.IntegerField(choices=RISK_CHOICES)
    #Service users assessed
    assessed_service_users = models.ManyToManyField(ServiceUser)
    #Staff users involved
    staff_users = models.ManyToManyField(User)
    #Linked log entry
    log_entry = models.OneToOneField(LogEntry, on_delete=models.CASCADE)


class NeighbourComplaints(models.Model):

    #Current date
    current_date = models.DateField(default=datetime.date.today)
    #Date of complaint
    complaint_date = models.DateField()
    #Time of complaint
    complaint_time = models.TimeField()
    #Name of complainant
    complainant_name = models.CharField(max_length=128)
    #Address of complainant
    complainant_address = models.TextField(max_length=1024, null=True, blank=True)
    #Telephone No. of complainant
    complainant_no = models.CharField(null=True, blank=True, max_length=16)
    #Staff user
    staff_user = models.ForeignKey(User, on_delete=models.CASCADE)
    #How was the complaint made
    complaint_type = models.CharField(max_length=256, null=True, blank=True)
    #Staff memner who recieved complaint
    recieved_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='neighbour_complaints_recieved')
    #Name of who complaint is regarding
    people_involved = models.CharField(max_length=1024, null=True, blank=True)
    #Address of where complaint is regarding
    complaint_address = models.TextField(max_length=1024, null=True, blank=True)
    #Telephone No. of complaint
    complaint_no = models.CharField(null=True, blank=True, max_length=16)
    #Complaint details
    complaint_details = models.TextField(max_length=1024, null=True, blank=True)
    #Managers response to complaint
    managers_response = models.TextField(max_length=1024, null=True, blank=True)
    #Feedback
    feedback = models.TextField(max_length=1024, null=True, blank=True)
    #Linked log entry
    log_entry = models.OneToOneField(LogEntry, on_delete=models.CASCADE)

logbook_cso/main/forms.py
from django import forms
from .models import *
from datetime import datetime as dt


# class to add date input
class DateInput(forms.DateInput):
    input_type = 'date'

	
#class to add time input
class TimeInput(forms.TimeInput):
    input_type = 'time'

	
class LogForm(forms.ModelForm):

  class Meta:
    model = LogEntry
    fields = '__all__'
    exclude = ('timestamp','assigned_user',)

	
class IncidentForm(forms.ModelForm):


  class Meta:
    model = IncidentReport
    fields = '__all__'
    widgets = {'incident_date': DateInput(), 'debriefing_meeting_date': DateInput(),'incident_time': TimeInput()}

	
#a form that takes a year from within the last five years from the user
class YearForm(forms.Form):

  year = forms.ChoiceField(choices=[(dt.now().year - y, dt.now().year - y) for y in range(6)])
	
	
class RiskForm(forms.ModelForm):

  class Meta:
    model = RiskAssessment
    fields = '__all__'
    widgets = {'review_date': DateInput()}

	
class ReferralForm(forms.ModelForm):

  class Meta:
    model = Referral
    fields = '__all__'
    widgets = {'dob': DateInput(),'referral_date': DateInput()}

	
class ServiceUserForm(forms.ModelForm):

  class Meta:
    model = ServiceUser
    fields = '__all__'
    widgets = {'date_accepted': DateInput()}

class UserUsesServiceForm(forms.ModelForm):

  class Meta:
    model = UserUsesService
    fields = ('service',)

	
class DiaryEntryForm(forms.ModelForm):

  class Meta:
    model = DiaryEntry
    fields = '__all__'
    widgets = {'appointment_date': DateInput()}

	
class NeighbourComplaintForm(forms.ModelForm):

  class Meta:
    model = NeighbourComplaints
    fields = '__all__'
    exclude = ('current_date',)
    widgets = {'complaint_date': DateInput(), 'complaint_time': TimeInput()}

	
class SocialWorkForm(forms.ModelForm):

  class Meta:
    model = SocialWork
    fields = '__all__'
    exclude = ('current_date',)

	
class VulnerableYoungAdultConcernsForm(forms.ModelForm):

  class Meta:
    model = VulnerableYoungAdultConcerns
    fields = '__all__'
    exclude = ('current_date',)
    widgets = {'date_of_birth': DateInput(), 'informed_date': DateInput()}

	
class ChildProtectionConcernForm(forms.ModelForm):

  class Meta:
    model = ChildProtectionConcern
    fields = '__all__'
    widgets = {'date_of_birth': DateInput(), 'mothers_date_of_birth': DateInput(), 'fathers_date_of_birth': DateInput(), 'date_of_concern': DateInput(), 'informed_date': DateInput()}

logbook_cso/templates/main/Service_User.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Service User
{% endblock %}

{% block body_block %}
	<br />
		<h1 class="service">{{ service_user }}</h1>
		
	<div class="container-fluid">
		<h4>
			{% for service in services.all %}
				{{ service.service }}
			{% endfor %}
		</h4>
		<div class="row">
  			<div class="col-md-3">
				<h4>National Insurance Number:</h4><p>{{ service_user.referral.nin }}</p>
				<h4>Gender:</h4> <p>{{ service_user.referral.get_gender_display}}</p>
				<h4>Emergency Contact:</h4><p> {{ service_user.referral.contact_name}}, phone {{ service_user.referral.contact_phone }}</p>
				<h4>Referral Date:</h4> <p> {{ service_user.referral.referral_date }}</p>
				<h4>Date Accepted:</h4> <p> {{service_user.userusesservice_set.all.0.start_date }}</p>
				<h4>Doctor:</h4><p> {{ service_user.referral.doctor_name }}, phone {{ service_user.referral.doctor_phone }}</p>
				<h4>Surgery Address:</h4> <p>{{ service_user.referral.surgery_address}}</p>
			</div>
			
  			<div class="col-md-3">
				<h4>Date of Birth:</h4><p> {{service_user.referral.dob }}</p>
				<h4>Phone Number:</h4><p> {{service_user.referral.phone }}</p>
				<h4>Referred By:</h4><p> {{service_user.referral.referred_by }}</p>
				<h4>Reason for referral:</h4><p> {{service_user.referral.reason }}</p>
				{% if service_user.referral.is_banned %}<h4 style="color:red">This person is banned</h4>{% endif %}

			</div>
			<div class="col-md-3">
				<h4>Health Issues:</h4> <p> {% if service_user.health_issues %}{{ service_user.health_issues }} {% else %} N/A {% endif %} </p>
				<h4>Drug Issues: </h4><p> {% if service_user.drug_issues %}{{ service_user.drug_issues }} {% else %} N/A {% endif %} </p>
				<h4>Emotional Issues:</h4><p> {% if service_user.emotional_issues %}{{ service_user.emotional_issues }} {% else %} N/A {% endif %} </p>
				{% if service_user.is_pregnant %}<h4>This person is pregnant</h4>{% endif %}
			</div>
			<div class="col-md-3">
				<h4>Mental Issues:</h4> <p> {% if service_user.mental_issues %}{{ service_user.mental_issues }} {% else %} N/A {% endif %} </p>
				<h4>Alcohol Issues:</h4> <p> {% if service_user.alcohol_issues %}{{ service_user.alcohol_issues }} {% else %} N/A {% endif %}</p>
				<h4>Criminal Background:</h4> <p> {% if service_user.criminal_background %}{{ service_user.criminal_background }} {% else %} N/A {% endif %} </p>
			</div>		
		</div>
		
		<div class="row">
		<div class="col-md-5">
		 	{% if service_user.referral.notes %} <h4>Notes:</h4><p> {{ service_user.referral.notes }}</p> {% endif %}
		</div>
		</div>
		<h4>Logs:</h4>
		<div class="scrollable">
			<div class="container-fluid">
					{% for value in logs %}
				<div class="panel-group">
						<div class="panel panel-default">
							<div id="centre" class="panel-heading">
								<h4 class="panel-title">
									{{ value.log }}
									<div style="height: 20px; width: 20px; background-color:{{ value.log.priority }}; border-radius:50%; border-width: 1px; border-style: solid; float: right"></div>
								</h4>
								<br>
								<p>
									{% if value.log.action_required %}
										<b>Action required</b><br>
									{% endif %}
									{{value.log.timestamp}}<br>
									{% if value.log.service_users.all %}
										Service users involved:
										{% for i in value.log.service_users.all %} <a href = "/main/service_user/{{i.id}}">{{ i }}</a>{% endfor %}<br>
									{% endif %}
									Description:
									{{value.log.description}}<br>
									{% if value.log.previous_log_entry %}
        								Linked to:
										{{value.log.previous_log_entry}} made on {{ value.log.timestamp }}<br>
    								{% endif %}
									Made by:
									{{value.log.assigned_user}}
								</p>
								{% if value.forms %}
                    				<a id="show_additional_{{ value.log.id }}"  class="get_log_details"  href="#log_{{ value.log.id }}" data-id="{{ value.log.id }}">Show Additional Details</a>
                    				<a hidden id="hide_additional_{{ value.log.id }}"  class="get_log_details"  href="#log_{{ value.log.id }}" data-id="{{ value.log.id }}">Hide Additional Details</a>
                				{% endif %}
							</div>
							<div id="log_{{ value.log.id }}" ></div>
						</div>
				</div>
				{% endfor %}
		</div>	
			
 			
			
		
	</div>
{% endblock %}

logbook_cso/templates/main/child_protection_concern_form.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Logbook
{% endblock %}
{% load widget_tweaks %}

{% block body_block %}

       <form id="log_form" method="post" action=""
              enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form -->

            <div class="modal-header"><h4><b>Add Child Protection Concern Form</b></h4></div>
            <div class="modal-body">
                {% for field in child_protection_concern_form %}
                <div class="in_app_form {% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>

            <!-- Provide a button to click to submit the form. -->
             <div class="modal-footer">
                <input type="submit" name="submit" value="Submit" id="about-btn" />   
            </div>
    </form>
{% endblock %}

logbook_cso/templates/main/diary.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Logbook
{% endblock %}

{% block body_block %}
<h2>Today is <span id=today></span>.</h2>
<hr>
<table ID="calendarTable" BORDER=1 ALIGN="center" width="85%" height="50%">
<tr>
    <th ID="tableHeader" COLSPAN=7></th>
</tr>
<tr><th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th>
<th>Thu</th><th>Fri</th><th>Sat</th></tr>
<tbody ID="tableBody"></tbody>
<tr>
    <td COLSPAN=7 align="center">
    <p>
    <form NAME="dateChooser">
        <select id="month_picker" NAME="chooseMonth">
            <option SELECTED>January<option>February
            <option>March<option>April<option>May
            <option>June<option>July<option>August
            <option>September<option>October
            <option>November<option>December
    </select>
    <select id="year_picker" NAME="chooseYear">
    </select>
    </form>
    </p></td>
</tr>
</table>
<hr>
<h2>UPCOMING EVENTS:</h2>
<div id="event_div" class="container-fluid"></div>
{% comment %}
<table ID="eventTable" BORDER=1 ALIGN="center">
<tr>
	<th>Event Date</th><th>Event Time</th><th>Young Person involved</th><th>Event Location</th><th>Event Details</th><th>Event created by</th>
</tr>
<tr>
	<td>The date of the event</td><td>Time of the Event</td>
	<td>The name of the young person the event is for</td>
	<td>Address of the event</td><td>Any additional details</td>
	<td>Name of staff member who added event</td>
</tr>
<tbody ID = "tableBody"></tbody>
{% endcomment %}
{% endblock %}

logbook_cso/templates/main/diary_entry_form.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Logbook
{% endblock %}
{% load widget_tweaks %}

{% block body_block %}

       <form id="log_form" method="post" action=""
              enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form -->

            <div class="modal-header"><h4><b>Add Diary Entry</b></h4></div>
            <div class="modal-body">
                {% for field in diary_entry_form %}
                <div class="in_app_form {% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>

            <!-- Provide a button to click to submit the form. -->
             <div class="modal-footer">
                <input type="submit" name="submit" value="Submit" id="about-btn" />   
            </div>
    </form>
{% endblock %}

logbook_cso/templates/main/diary_event.html
{% if events %}
	{% for event in events %}
	<div class="panel-group">
        <div class="panel panel-default">
            <div id="centre" class="panel-heading">
               <p>
					Appointment Date: {{ event.appointment_date }}<br>
					Details: {{ event.details }}<br>
					{% if event.service_user %} Service User: {{ event.service_user }}<br> {% endif %}
					Staff User: {{ event.staff_user }}
				</p> 
            </div>
        </div>
    </div>
    <br>
	{% endfor %}
{% else %}
	No events
{% endif %}

logbook_cso/templates/main/graphs.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Graphs
{% endblock %}

{% block body_block %}
	{% if no_service_users %}
		<h3 style="text-align: center">There are currently no registered service users.</h3>
	{% else %}
		<form id="year_form" method="post" action=""
				  enctype="multipart/form-data">

				{% csrf_token %}
				Choose a Year:
				{{ year_form.as_p }}<br>

		<input type="Submit" name="Submit" value="Submit" />
		</form>

			<img src="{% static graph %}">
	{% endif %}
{% endblock %}
				

logbook_cso/templates/main/homepage1.html
<!DOCTYPE html>
<html>

{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
      integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/general.css' %}">
{% comment %}
../static/css/general.css
../static/images/odap2.png
{% endcomment %}

<head>
    <title>

        ODAP

    </title>
</head>
<body>


<ul class="topnav">
    <li><a id="logo" href="" class="navbar-brand"><img id="logoimg" src="{% static 'images/odap-new.jpeg' %}" width="60"
                                                       height="60" alt="" class="d-inline-block align-top"/>
        <p class="right b">Open Door Accommodation Project</p></a></li>


</ul>


<div class="center">
    <div class="main container text-center"><br/>
        <h1 class="login"><strong>Welcome to OpenBook</strong></h1><br/>

        <!-- login form-->

        <form method="POST" action="" role="form">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input id="username" type="text" placeholder="Username" name="username" class="form-control"/>
            </div>
            <br/>
            <div class="form-group">
                <label for="password">Password:</label>
                <input id="password" type="password" placeholder="Password" name="password" class="form-control"/>
            </div>
            <br/>
            <button type="submit" class="btn btn-success" value="Login">Log In</button>
        </form>
        <br/>

        {% if invalid %}<p>Invalid login details</p>{%endif%}
        <p><a href="{% url 'password_reset' %}">Reset password</a></p>

    </div>
</div>


</body>
</html>

logbook_cso/templates/main/incident_form.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Add Incident report
{% endblock %}
{% load widget_tweaks %}

{% block body_block %}

       <form id="log_form" method="post" action=""
              enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form -->
            
            <div class="modal-header"><h4><b>Add Incident Report</b></h4></div>
            <div class="modal-body">
                {% for field in incident_form %}
                <div class="in_app_form {% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            
            <!-- Provide a button to click to submit the form. -->
             <div class="modal-footer">
                <input type="submit" name="submit" value="Submit" id="about-btn" />   
            </div>
    </form>
{% endblock %}

logbook_cso/templates/main/neighbour_complaint_form.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Logbook
{% endblock %}
{% load widget_tweaks %}

{% block body_block %}

       <form id="log_form" method="post" action=""
              enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form -->

            <div class="modal-header"><h4><b>Add Neighbour Complaint</b></h4></div>
            <div class="modal-body">
                {% for field in neighbour_complaint_form %}
                <div class="in_app_form {% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>

            <!-- Provide a button to click to submit the form. -->
             <div class="modal-footer">
                <input type="submit" name="submit" value="Submit" id="about-btn" />   
            </div>
    </form>
{% endblock %}